### ISSUE TITLE
Feedback for "Creating a menu of geo objects collections with Yandex.Maps API and BEM"

### ISSUE THREAD

**Issue by tormozz48** [zloylos/ymapsbem#3]
Please fix your link zloylos.github.io/ymapsbem/index-en.html. by adding the http:// protocol prefix

correct example:
http://zloylos.github.io/ymapsbem/index-en.html

It will fix your link on bem.info site

**Comment by tormozz48** [comment]
@zloylos

**Comment by gela-d** [comment]
My PR to close this issue - https://github.com/zloylos/ymapsbem/pull/4
